### PR TITLE
#12 Update pgdeploy as a python3 compatible version

### LINKED ISSUE #12: Add pgdeploy3 as a python3 version
Rel https://github.com/Proemion/puppet/issues/1639

### PR DESCRIPTION
**Pull request by jamie-staib**
Fixes #12 

Only changes needed were on print() statements and the except syntax.

### CODE REVIEW

**Comment by Svedrin** [comment]
@jamie-staib rather than creating a new version, how about we just convert the existing one? we don't have any servers where Py3 is not available anymore, do we?

**Comment by jamie-staib** [comment]
@Svedrin I was not 100% sure of the impact of pgdeploy. I think that it is only used now to point pgbouncer to the master after a switchover, and we have very few loads going through the pgbouncers now, so risk may be minimal.

It would certainly simplify all the changes, also at the repmgr puppet module side, so if you think it's a reasonable risk, lets go for it.

**Comment by Svedrin** [comment]
@jamie-staib yep, let's do that :slightly_smiling_face: even _if_ we run into a system that only has Python 2, as long as it's python 2.7, the script will just work there as well.

**Comment by jamie-staib** [comment]
@Svedrin Will update the PR then.

Only thing, as I will need to change the repmgr puppet module to install the python3 prereq libraries, and to make sure that python3 was being used would also change the shebang to python3, the new script will not work if the system does not have python3.

**Comment by jamie-staib** [comment]
Pushed changes. @Svedrin  A bit undecided on the shebang. This feels safer than keeping python and changing the default to python3.

**Review by Svedrin — APPROVED** [review]
@jamie-staib LGTM, thanks!

**Pull request merged**
